FROM node:22

WORKDIR /app
COPY ./server/package.json ./server/pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install

RUN pnpm install --prod
RUN pnpm run build

EXPOSE 3000
CMD ["pnpm", "start"]
